### ISSUE TITLE
Branching Model / Workflow

### ISSUE THREAD

**Issue by lazaridiscom** [goerli/parity-goerli#48]
## Feature-Branches etc.

Is there a list of the branches which contain the work of the developers working on parity-clique?

## Merging to upstream

I noticed that the existent PR (https://github.com/paritytech/parity-ethereum/pull/9981) goes directly against parity/master.

Is the plan to stabilize (production grade) `parity-goerli/master`, and then merge it in one-chunk into parity-ethereum/master?

## Docs

Is the Branching Model / Workflow documented anywhere?

**Comment by 5chdn** [comment]
1) I just removed stale branches, check https://github.com/goerli/parity-goerli/branches
2) Yes, the idea is to stabilize our master to merge it upstream
3) I'm personally using simplified gitflow: feature branch --> master branch

we don't do releases or anything else but features --> master (master is here: "develop")

**Comment by lazaridiscom** [comment]
(ok for now, but please reopen, I need to revisit this issue)
