### ISSUE TITLE
You behave like Fascists!!!

### ISSUE THREAD

**Issue by lazaridiscom** [goerli/parity-goerli#60]
What is this here? Are you serious?

https://github.com/goerli/parity-goerli/issues/44#issuecomment-472115447

@thefallentree communicates openly and honestly. he may has not the best diplomacy, but anyone can read his statements and assess them.

And you spread warnings and go one with censoring?

Just unacceptable behavior of the goerli project and its members. 

You folks should really be ashamed.

Decentralization and crap.

This is centralization in its purest form.

.

**Comment by soc1c** [comment]
Thanks for your feedback. Please, refer to our code of conduct before further engaging in this discussion.
