### ISSUE TITLE
CI/Travis is not working anymore

### ISSUE THREAD

**Issue by jleni** [goerli/parity-goerli#81]
Copied over here for better visibility/tracking:

> This change https://github.com/goerli/parity-goerli/pull/76  disables CI and travis does not build PRs anymore
> 
> Some alternatives:
> Best: politely ask parity if they mind having that file in their repo. In practice any external team contributing but without access to gitlab would find that useful.
> Plan B: branch parity-goerly/master to upstream_pr and adjust things only there?
> Plan Z: keep this file until the last moment so we dont lose CI.
>

**Comment by soc1c** [comment]
once cliue is merged you can submit your PR upstream and use the parity CI

**Comment by soc1c** [comment]
we can start working on upstream now https://github.com/paritytech/parity-ethereum
