### ISSUE TITLE
Returning block.nonce from rpc

### ISSUE THREAD

**Issue by mpetrunic** [goerli/parity-goerli#86]
- **Parity Ethereum version**: clique-v5
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: goerli

Since for clique block.nonce field is used for voting, it would be useful to get it with `eth_getBlockByHash` or `eth_getBlockByNumber`. Currently that field is excluded from response since it's not needed for rest of POA networks. (https://wiki.parity.io/JSONRPC-eth-module#eth_getblockbyhash)

**Comment by soc1c** [comment]
Can you create that ticket upstream? https://github.com/paritytech/parity-ethereum

**Comment by mpetrunic** [comment]
[Upstream ticket #10534](https://github.com/paritytech/parity-ethereum/issues/10534)
